name: Keep Streamlit Awake

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 mins
  workflow_dispatch:      # manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        run: curl -s -o /dev/null -w "%{http_code}" https://suryaseodashboard.streamlit.app/
